# Font style metadata
name = "data_warz"

# Optional Google font URL
google_fonts = ""

# Font families
heading_font = "Lora"
body_font = "Fira Sans"
nav_font = "Audiowide"
mono_font = "Roboto Mono"

# Font size
font_size = "18"
font_size_small = "16"
